---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/henric05/lights.henricruz.com.br/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH